name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Upload index.html
        uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: BioSecurePay.github.io/templates/index.html

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site-artifact
          path: path/to/artifact

      - name: Open index.html
        run: |
          cat path/to/artifact/index.html
